package api.entity;

import java.io.Serializable;
import java.util.Date;

public class SecurityDepositPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.platform_id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.tag_num
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Integer tagNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.platform_tag
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Integer platformTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.credit
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.create_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_security_deposit.update_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_security_deposit
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.id
     *
     * @return the value of platform_security_deposit.id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.id
     *
     * @param id the value for platform_security_deposit.id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.platform_id
     *
     * @return the value of platform_security_deposit.platform_id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.platform_id
     *
     * @param platformId the value for platform_security_deposit.platform_id
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.tag_num
     *
     * @return the value of platform_security_deposit.tag_num
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Integer getTagNum() {
        return tagNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.tag_num
     *
     * @param tagNum the value for platform_security_deposit.tag_num
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setTagNum(Integer tagNum) {
        this.tagNum = tagNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.platform_tag
     *
     * @return the value of platform_security_deposit.platform_tag
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Integer getPlatformTag() {
        return platformTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.platform_tag
     *
     * @param platformTag the value for platform_security_deposit.platform_tag
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setPlatformTag(Integer platformTag) {
        this.platformTag = platformTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.credit
     *
     * @return the value of platform_security_deposit.credit
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.credit
     *
     * @param credit the value for platform_security_deposit.credit
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.create_time
     *
     * @return the value of platform_security_deposit.create_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.create_time
     *
     * @param createTime the value for platform_security_deposit.create_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_security_deposit.update_time
     *
     * @return the value of platform_security_deposit.update_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_security_deposit.update_time
     *
     * @param updateTime the value for platform_security_deposit.update_time
     *
     * @mbg.generated Tue Mar 13 20:34:58 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}